INFO:root:Created superhero Superman
INFO:root:Created superhero Superman
INFO:root:Created superhero Wonder Woman
INFO:root:Created superhero Wonder Woman
INFO:root:Created superhero Spider-Man
INFO:root:Created superhero Spider-Man
INFO:root:Created superhero Iron Man
INFO:root:Created superhero Iron Man
WARNING:django.request:Not Found: /superheroes/{% static 'js/superheroes.js'
WARNING:django.request:Not Found: /superheroes/{% static 'js/superheroes.js'
ERROR:django.request:Internal Server Error: /superheroes/demoform
Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jstrick/Documents/curr/courses/python/examples3/django1.11/djform/superheroes/views.py", line 34, in demoform
    return render(request, 'forms/forms_fields_demo.html', context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: forms/forms_fields_demo.html
WARNING:django.request:Not Found: /superheroes/{% static 'js/superheroes.js'
WARNING:django.request:Not Found: /superheroes/{% static 'js/superheroes.js'
WARNING:django.request:Not Found: /forms/fields_demo/
WARNING:django.request:Not Found: /superheroes/{% static 'js/superheroes.js'
WARNING:django.request:Not Found: /forms/fields_demo/
WARNING:django.request:Not Found: /superheroes/{% static 'js/superheroes.js'
WARNING:django.request:Not Found: /superheroes/{% static 'js/superheroes.js'
WARNING:django.request:Not Found: /superheroes/formdemo
WARNING:django.request:Not Found: /superheroes/formdemo
WARNING:django.request:Not Found: /superheroes/formdemo
WARNING:django.request:Not Found: /superheroes/{% static 'js/superheroes.js'
WARNING:django.request:Not Found: /superheroes/{% static 'js/superheroes.js'
WARNING:django.request:Not Found: /superheroes/views.demoform
WARNING:django.request:Not Found: /superheroes/views.demoform
WARNING:django.request:Not Found: /superheroes/views.demoform
WARNING:django.request:Not Found: /superheroes/{% static 'js/superheroes.js'
WARNING:django.request:Not Found: /superheroes/{% static 'js/superheroes.js'
WARNING:django.request:Not Found: /superheroes/{% static 'js/superheroes.js'
WARNING:django.request:Not Found: /superheroes/{% static 'js/superheroes.js'
WARNING:django.request:Not Found: /superheroes/{% static 'js/superheroes.js'
ERROR:django.request:Internal Server Error: /superheroes/demoform
Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jstrick/Documents/curr/courses/python/examples3/django1.11/djform/superheroes/views.py", line 36, in demoform
    return render(request, 'form_demo.html', context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 312, in do_extends
    nodelist = parser.parse()
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 255, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/defaulttags.py", line 989, in do_if
    raise TemplateSyntaxError('Malformed template tag at line {0}: "{1}"'.format(token.lineno, token.contents))
django.template.exceptions.TemplateSyntaxError: Malformed template tag at line 9: "endif invalid"
ERROR:django.request:Internal Server Error: /superheroes/demoform
Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jstrick/Documents/curr/courses/python/examples3/django1.11/djform/superheroes/views.py", line 19, in demoform
    context.extend(
AttributeError: 'dict' object has no attribute 'extend'
ERROR:django.request:Internal Server Error: /superheroes/heroform
Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: heroform() missing 1 required positional argument: 'form_type'
ERROR:django.request:Internal Server Error: /superheroes/heroform
Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 154, in render
    compiled_parent = self.get_parent(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 151, in get_parent
    return self.find_template(parent, context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 131, in find_template
    template_name, skip=history,
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/engine.py", line 148, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: queries/queries_base_boot.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jstrick/Documents/curr/courses/python/examples3/django1.11/djform/superheroes/views.py", line 63, in heroform
    return render(request, 'hero_select.html', context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 68, in render
    reraise(exc, self.backend)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 89, in reraise
    six.reraise(exc.__class__, new, sys.exc_info()[2])
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 154, in render
    compiled_parent = self.get_parent(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 151, in get_parent
    return self.find_template(parent, context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 131, in find_template
    template_name, skip=history,
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/engine.py", line 148, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: queries/queries_base_boot.html
WARNING:django.request:Not Found: /forms/select/
WARNING:django.request:Not Found: /forms/select/
WARNING:django.request:Not Found: /demoform
WARNING:django.request:Not Found: /superheroes/select/
ERROR:django.request:Internal Server Error: /superheroes/heroform/
Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jstrick/Documents/curr/courses/python/examples3/django1.11/djform/superheroes/views.py", line 51, in heroform
    'form_type': form_type,
NameError: name 'form_type' is not defined
WARNING:django.request:Not Found: /superheroes/modelform/
WARNING:django.request:Not Found: /superheroes/modelform/
WARNING:django.request:Not Found: /superheroes/modelform
WARNING:django.request:Not Found: /superheroes/modelform/
WARNING:django.request:Not Found: /superheroes/modelform/
WARNING:django.request:Not Found: /
WARNING:django.request:Not Found: /
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /
WARNING:django.request:Not Found: /
WARNING:django.request:Not Found: /superheroes/superman
